### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by aminbabar** [cracine79/renoun#4]
- [x] State shape is flat!
- [x] State’s keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by SiegeTheDay90** [comment]
There are some missing commas in between items. 
On the frontend, keys like `seller_id` would be named `selledId` by convention.
Managing carts is more efficient if we use a `cart_items` joins table. In the example below, User 2 has two items in their cart with different amounts of each item.
```json
cartItems: {
    1: {
            id: 1, 
            buyerId: 2, // user 2
            partId: 3, // part 3
            count: 5, // There are 5 of this item in the cart
        },

    2: {
            id: 2, 
            buyerId: 2, // user 2
            partId: 4, // part 4
            count: 1, // There are 1 of this item in the cart
        },
}```
