### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by aminbabar** [cracine79/renoun#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

**Comment by SiegeTheDay90** [comment]
Small typo `GET /api/users/:id` at the beginning.
Not sure how `POST /api/watches` will create a follow? Will it need an `:id` param?

**Comment by cracine79** [comment]
Typo fixed!  Watches are like likes - make a connection between user and instrument.  I think I can just pass the user_id and instrument_id through in the body of the fetch request?
